<?php

declare(strict_types=1);

namespace XArrPay;

use XArrPay\Http\Controllers\EpayController;
use XArrPay\Http\Controllers\HealthController;
use XArrPay\Http\Controllers\InstallController;
use XArrPay\Http\Controllers\AdminController;
use XArrPay\Http\Controllers\PayController;
use XArrPay\Http\Controllers\MerchantController;
use XArrPay\Http\Controllers\AdminFeatureController;
use XArrPay\Http\Controllers\MerchantFeatureController;
use XArrPay\Http\Request;
use XArrPay\Http\Router;
use XArrPay\Support\InstallState;
use XArrPay\Support\RuntimeLogger;

final class Application
{
    public function run(): never
    {
        $request = new Request();
        InstallState::enforce($request->path());
        RuntimeLogger::recordAdminRequest($request);
        $health = new HealthController();
        $install = new InstallController();
        $epay = new EpayController();
        $admin = new AdminController();
        $pay = new PayController();
        $merchant = new MerchantController();
        $adminFeature = new AdminFeatureController();
        $merchantFeature = new MerchantFeatureController();
        $router = new Router();

        $router->get('/api/system/timestamp', fn () => $health->timestamp());
        $router->get('/api/health', fn () => $health->health());
        $router->get('/api/install/progress', fn () => $install->progress());
        $router->get('/api/install/conf', fn () => $install->conf());
        $router->post('/api/install/authorize', fn (Request $request) => $install->authorize($request));
        $router->post('/api/install/database', fn (Request $request) => $install->database($request));
        $router->get('/api/install/init', fn (Request $request) => $install->init($request));
        $router->post('/api/install/basic', fn (Request $request) => $install->basic($request));
        $router->post('/api/install/end', fn () => $install->end());
        $router->get('/api/config', fn () => $admin->config());
        $router->get('/api/login/connect', fn () => $admin->loginConnect());
        $router->get('/api/login/channels', fn () => $admin->loginChannels());
        $router->get('/api/login/captcha', fn () => $admin->captcha());
        $router->post('/api/login', fn (Request $request) => $merchant->login($request));
        $router->post('/api/login/safe', fn (Request $request) => $merchant->loginMfa($request));
        $router->get('/api/login/qrcode', fn (Request $request) => $merchant->loginQrcode($request));
        $router->post('/api/login/passkey/begin', fn (Request $request) => $merchant->passkeyLoginBegin($request));
        $router->post('/api/login/passkey/finish', fn (Request $request) => $merchant->passkeyLoginFinish($request));
        $router->get('/api/qrcode', fn (Request $request) => $merchant->qrcode($request));
        $router->post('/api/qrcode/decode', fn (Request $request) => $merchant->decodeQrcode($request));
        $router->post('/api/captcha/gen', fn (Request $request) => $merchantFeature->captchaGen($request));
        $router->post('/api/captcha/valid', fn (Request $request) => $merchantFeature->captchaValid($request));
        $router->post('/api/security/step-up/begin', function (Request $request) use ($admin, $merchantFeature): never {
            if ($admin->isStaffToken($request)) {
                $admin->stepUpBegin($request);
            }
            $merchantFeature->stepUpBegin($request);
        });
        $router->post('/api/security/step-up/finish', function (Request $request) use ($admin, $merchantFeature): never {
            if ($admin->isStaffToken($request)) {
                $admin->stepUpFinish($request);
            }
            $merchantFeature->stepUpFinish($request);
        });
        $router->post('/api/security/step-up/send-code', function (Request $request) use ($admin, $merchantFeature): never {
            if ($admin->isStaffToken($request)) {
                $admin->stepUpSendCode($request);
            }
            $merchantFeature->stepUpSendCode($request);
        });
        $router->post('/api/ws/ticket', fn (Request $request) => $merchantFeature->webSocketTicket($request));
        $router->get('/api/user/profile', fn (Request $request) => $merchant->profile($request));
        $router->get('/api/staff/profile', fn (Request $request) => $admin->profile($request));
        $router->get('/api/pay-type/list', fn (Request $request) => $merchant->payTypes($request));
        $router->get('/api/channel/list', fn (Request $request) => $merchant->channels($request));
        $router->get('/api/channel/form-items', fn (Request $request) => $merchant->channelFormItems($request));
        $router->get('/api/channel/gateway', fn (Request $request) => $merchant->channelGateways($request));
        $router->get('/api/channel/account/list', fn (Request $request) => $merchant->channelAccounts($request));
        $router->get('/api/order/list', fn (Request $request) => $merchant->orders($request));
        $router->get('/api/statistics/info', fn (Request $request) => $merchant->statistics($request));
        $router->get('/api/static/order/base', fn (Request $request) => $merchant->orderBase($request));
        $router->get('/api/static/pay-type', fn (Request $request) => $merchant->staticPayTypes($request));
        $router->get('/api/static/pay-hour-stats', fn (Request $request) => $merchant->payHourStats($request));
        $router->get('/api/static/pay-daily-stats', fn (Request $request) => $merchant->payDailyStats($request));
        $router->get('/api/notice/show', fn (Request $request) => $merchant->noticeShow($request));
        $router->get('/api/notice/shows', fn (Request $request) => $merchant->noticeShows($request));
        $router->get('/api/notice/detail', fn (Request $request) => $merchant->noticeDetail($request));
        $router->post('/api/user/reset-pwd', fn (Request $request) => $merchant->resetPassword($request));
        $router->post('/api/user/reset-secret', fn (Request $request) => $merchant->resetSecret($request));
        $router->get('/api/user/secret', fn (Request $request) => $merchant->secret($request));
        $router->get('/api/log/balance', fn (Request $request) => $merchant->balanceLogs($request));
        $router->get('/api/log/login', fn (Request $request) => $merchant->loginLogs($request));
        $router->get('/api/log/notify', fn (Request $request) => $merchant->notifyLogs($request));
        $router->post('/api/log/notify/batch-remove', fn (Request $request) => $merchant->batchRemoveNotifyLogs($request));
        $router->post('/api/log/notify/batch-clean', fn (Request $request) => $merchant->batchCleanNotifyLogs($request));
        $router->get('/api/user/withdraw-account/list', fn (Request $request) => $merchant->withdrawAccounts($request));
        $router->post('/api/user/withdraw-account/save', fn (Request $request) => $merchant->saveWithdrawAccount($request));
        $router->post('/api/user/withdraw-account/remove', fn (Request $request) => $merchant->removeWithdrawAccount($request));
        $router->get('/api/user/withdraw-income/list', fn (Request $request) => $merchant->withdrawIncomeList($request));
        $router->post('/api/user/withdraw-income/create', fn (Request $request) => $merchant->createWithdrawIncome($request));
        $router->get('/api/user/withdraw-income/config', fn (Request $request) => $merchant->withdrawIncomeConfig($request));
        $router->post('/api/recharge/create', fn (Request $request) => $merchant->createRecharge($request));
        $router->get('/api/recharge/status', fn (Request $request) => $merchant->rechargeStatus($request));
        $router->post('/api/recharge/use-card', fn (Request $request) => $merchant->useRechargeCard($request));
        $router->any('/api/recharge/notify', fn (Request $request) => $merchant->rechargeNotify($request));
        $router->get('/api/channel/account/detail', fn (Request $request) => $merchant->channelAccountDetail($request));
        $router->post('/api/channel/account/create', fn (Request $request) => $merchant->createChannelAccount($request));
        $router->post('/api/channel/account/edit', fn (Request $request) => $merchant->editChannelAccount($request));
        $router->post('/api/channel/account/remove', fn (Request $request) => $merchant->removeChannelAccount($request));
        $router->post('/api/channel/account/switch-status', fn (Request $request) => $merchant->switchChannelAccountStatus($request));
        $router->post('/api/channel/account/copy', fn (Request $request) => $merchant->copyChannelAccount($request));
        $router->post('/api/channel/account/plugin-action', fn (Request $request) => $merchant->channelAccountPluginAction($request));
        $router->post('/api/channel/account/qrcode-login/qrcode', fn (Request $request) => $merchant->channelAccountQrcodeLogin($request));
        $router->post('/api/channel/account/qrcode-login/check', fn (Request $request) => $merchant->channelAccountQrcodeLoginCheck($request));
        $router->get('/api/channel/account/batch-import', fn (Request $request) => $merchant->batchImportInfo($request));
        $router->post('/api/channel/account/batch-import', fn (Request $request) => $merchant->batchImportAccounts($request));
        $router->get('/api/polling/list', fn (Request $request) => $merchantFeature->pollingList($request));
        $router->post('/api/polling/create', fn (Request $request) => $merchantFeature->pollingWrite($request));
        $router->post('/api/polling/edit', fn (Request $request) => $merchantFeature->pollingWrite($request, (int) $request->input('id', 0)));
        $router->post('/api/polling/remove', fn (Request $request) => $merchantFeature->pollingRemove($request));
        $router->post('/api/polling/switch-status', fn (Request $request) => $merchantFeature->pollingSwitch($request));
        $router->get('/api/polling/channel', fn (Request $request) => $merchantFeature->pollingChannel($request));
        $router->post('/api/polling/save-channel', fn (Request $request) => $merchantFeature->pollingSaveChannel($request));
        $router->get('/api/setting/pay', fn (Request $request) => $merchantFeature->paySettings($request));
        $router->post('/api/setting/pay', fn (Request $request) => $merchantFeature->paySettings($request, true));
        $router->get('/api/pay/templates', fn (Request $request) => $merchantFeature->payTemplates($request));
        $router->post('/api/pay/set-template', fn (Request $request) => $merchantFeature->setPayTemplate($request));
        $router->get('/api/cashier/uri', fn (Request $request) => $merchantFeature->cashierUri($request));
        $router->get('/api/meal/list', fn (Request $request) => $merchantFeature->mealList($request));
        $router->post('/api/meal/buy', fn (Request $request) => $merchantFeature->mealBuy($request));
        $router->post('/api/user/meal/auto-renewal-switch', fn (Request $request) => $merchantFeature->mealAutoRenewalSwitch($request));
        $router->get('/api/user/shared-channel/settlement/list', fn (Request $request) => $merchantFeature->sharedChannelSettlementList($request));
        $router->get('/api/push/events', fn (Request $request) => $merchantFeature->pushEvents($request));
        $router->get('/api/setting/event-notice', fn (Request $request) => $merchantFeature->eventNotice($request));
        $router->post('/api/setting/event-notice', fn (Request $request) => $merchantFeature->eventNotice($request, true));
        $router->get('/api/setting/scenes-safe', fn (Request $request) => $merchantFeature->safeSettings($request, 'scenes'));
        $router->post('/api/setting/scenes-safe', fn (Request $request) => $merchantFeature->safeSettings($request, 'scenes', true));
        $router->get('/api/setting/setting-safes', fn (Request $request) => $merchantFeature->safeSettings($request, 'settings'));
        $router->post('/api/setting/setting-safes', fn (Request $request) => $merchantFeature->safeSettings($request, 'settings', true));
        $router->get('/api/pay-codes/list', fn (Request $request) => $merchantFeature->payCodeList($request));
        $router->post('/api/pay-codes/create', fn (Request $request) => $merchantFeature->payCodeWrite($request));
        $router->post('/api/pay-codes/edit', fn (Request $request) => $merchantFeature->payCodeWrite($request, (int) $request->input('id', 0)));
        $router->post('/api/pay-codes/remove', fn (Request $request) => $merchantFeature->payCodeRemove($request));
        $router->post('/api/pay-codes/switch-status', fn (Request $request) => $merchantFeature->payCodeSwitch($request));
        $router->get('/api/qrcode-templates/list', fn (Request $request) => $merchantFeature->payTemplates($request));
        $router->get('/api/domain-white/list', fn (Request $request) => $merchantFeature->domainWhiteList($request));
        $router->post('/api/domain-white/apply', fn (Request $request) => $merchantFeature->domainWhiteApply($request));
        $router->get('/api/invite/info', fn (Request $request) => $merchantFeature->inviteInfo($request));
        $router->post('/api/invite/rebate_record', fn (Request $request) => $merchantFeature->inviteRebateRecord($request));
        $router->get('/api/invite/rebate_record', fn (Request $request) => $merchantFeature->inviteRebateRecord($request));
        $router->post('/api/invite/transfer_rebate', fn (Request $request) => $merchantFeature->transferRebate($request));
        $router->get('/api/mcp/keys', fn (Request $request) => $merchantFeature->mcpKeys($request));
        $router->post('/api/mcp/keys/create', fn (Request $request) => $merchantFeature->mcpKeys($request, 'create'));
        $router->post('/api/mcp/keys/update', fn (Request $request) => $merchantFeature->mcpKeys($request, 'update'));
        $router->post('/api/mcp/keys/status', fn (Request $request) => $merchantFeature->mcpKeys($request, 'status'));
        $router->post('/api/mcp/keys/settings', fn (Request $request) => $merchantFeature->mcpKeys($request, 'settings'));
        $router->post('/api/mcp/keys/delete', fn (Request $request) => $merchantFeature->mcpKeys($request, 'delete'));
        $router->get('/api/user/verification/config', fn (Request $request) => $merchantFeature->verification($request, 'config'));
        $router->get('/api/user/verification/status', fn (Request $request) => $merchantFeature->verification($request, 'status'));
        $router->get('/api/user/verification/info', fn (Request $request) => $merchantFeature->verification($request, 'info'));
        $router->post('/api/user/verification/personal', fn (Request $request) => $merchantFeature->verification($request, 'personal'));
        $router->post('/api/user/verification/create', fn (Request $request) => $merchantFeature->verificationCreate($request));
        $router->post('/api/user/verification/upload-face', fn (Request $request) => $merchantFeature->verificationUpload($request, 'face'));
        $router->post('/api/user/verification/upload-idcard', fn (Request $request) => $merchantFeature->verificationUpload($request, 'idcard'));
        $router->post('/api/user/verification/send-phone-code', fn (Request $request) => $merchantFeature->verification($request, 'send-phone-code'));
        $router->post('/api/user/verification/verify-phone-code', fn (Request $request) => $merchantFeature->verification($request, 'verify-phone-code'));
        $router->get('/api/user/verification/ticket/status', fn (Request $request) => $merchantFeature->verification($request, 'ticket-status'));
        $router->post('/api/order/remove', fn (Request $request) => $merchant->removeOrder($request));
        $router->post('/api/order/batch-remove', fn (Request $request) => $merchant->batchRemoveOrders($request));
        $router->post('/api/order/close', fn (Request $request) => $merchant->closeOrder($request));
        $router->post('/api/order/wait', fn (Request $request) => $merchant->waitOrder($request));
        $router->post('/api/order/success', fn (Request $request) => $merchant->successOrder($request));
        $router->post('/api/order/callback', fn (Request $request) => $merchant->callbackOrder($request));
        $router->post('/api/order/create-test', fn (Request $request) => $merchant->createTestOrder($request));
        $router->get('/api/plugins/list', fn (Request $request) => $merchant->plugins($request));
        // The admin bundle prefixes management API calls with /api/admin when
        // admin_path is "admin". Keep this namespace explicit and separate
        // from the merchant-facing API above.
        $router->get('/api/admin/config', fn () => $admin->config());
        $router->get('/api/admin/login/connect', fn () => $admin->loginConnect());
        $router->get('/api/admin/login/captcha', fn () => $admin->captcha());
        $router->post('/api/admin/login', fn (Request $request) => $admin->login($request));
        $router->get('/api/admin/staff/profile', fn (Request $request) => $admin->profile($request));
        $router->post('/api/admin/security/step-up/begin', fn (Request $request) => $admin->stepUpBegin($request));
        $router->post('/api/admin/security/step-up/finish', fn (Request $request) => $admin->stepUpFinish($request));
        $router->post('/api/admin/security/step-up/send-code', fn (Request $request) => $admin->stepUpSendCode($request));
        $router->get('/api/admin/staff/connect-channels', fn (Request $request) => $adminFeature->staffConnectChannels($request));
        $router->get('/api/admin/staff/passkey/list', fn (Request $request) => $adminFeature->staffPasskeyList($request));
        $router->get('/api/admin/pay-type/list', fn (Request $request) => $admin->payTypes($request));
        $router->get('/api/admin/channel/list', fn (Request $request) => $admin->channels($request));
        $router->get('/api/admin/channel/account/list', fn (Request $request) => $admin->channelAccounts($request));
        $router->get('/api/admin/order/list', fn (Request $request) => $admin->orders($request));
        $router->get('/api/admin/user/list', fn (Request $request) => $admin->users($request));
        $router->get('/api/admin/notice/list', fn (Request $request) => $admin->notices($request));
        $router->get('/api/admin/balance/list', fn (Request $request) => $admin->balanceLogs($request));
        $router->get('/api/admin/log/notify', fn (Request $request) => $admin->notifyLogs($request));
        $router->get('/api/admin/notify/queue', fn (Request $request) => $admin->notifyQueue($request));
        $router->post('/api/admin/notify/queue/retry', fn (Request $request) => $admin->retryNotifyQueue($request));
        $router->get('/api/admin/withdraw-income/list', fn (Request $request) => $admin->withdrawIncomeList($request));
        $router->post('/api/admin/withdraw-income/audit', fn (Request $request) => $admin->auditWithdrawIncome($request));
        $router->post('/api/admin/withdraw-income/mark-paid', fn (Request $request) => $admin->markWithdrawPaid($request));
        $router->post('/api/admin/withdraw-income/mark-failed', fn (Request $request) => $admin->markWithdrawFailed($request));
        $router->get('/api/admin/option/withdraw', fn (Request $request) => $admin->withdrawOption($request));
        $router->post('/api/admin/option/withdraw', fn (Request $request) => $admin->saveWithdrawOption($request));
        $router->get('/api/admin/statistics/info', fn (Request $request) => $admin->statistics($request));
        $router->get('/api/admin/plugins/list', fn (Request $request) => $admin->plugins($request));
        $router->get('/api/admin/pay/conf', fn (Request $request) => $admin->payConf($request));
        $router->get('/api/admin/home/info', fn (Request $request) => $admin->homeInfo($request));
        $router->get('/api/admin/home/pay-distribution', fn (Request $request) => $admin->homePayDistribution($request));
        $router->get('/api/admin/home/merchant-register', fn (Request $request) => $admin->homeMerchantRegister($request));
        $router->get('/api/admin/home/order-amount', fn (Request $request) => $admin->homeOrderAmount($request));
        $router->get('/api/admin/home/daily-recharge', fn (Request $request) => $admin->homeDailyRecharge($request));
        $router->get('/api/admin/home/merchant-ranking', fn (Request $request) => $admin->homeMerchantRanking($request));
        $router->get('/api/admin/home/authorize', fn (Request $request) => $admin->homeAuthorize($request));
        $router->get('/api/admin/home/safe-rate', fn (Request $request) => $admin->homeSafeRate($request));
        $router->get('/api/admin/system/info', fn (Request $request) => $admin->systemInfo($request));
        $router->get('/api/admin/system/redis/status', fn (Request $request) => $admin->redisStatus($request));
        $router->get('/api/admin/log/files', fn (Request $request) => $adminFeature->logFiles($request));
        $router->get('/api/admin/log/detail', fn (Request $request) => $adminFeature->logDetail($request));
        $router->get('/api/admin/log/download', fn (Request $request) => $adminFeature->logDownload($request));
        $router->match(['GET', 'POST'], '/api/admin/log/remove', fn (Request $request) => $adminFeature->logRemove($request));
        $router->post('/api/admin/log/batch-remove', fn (Request $request) => $adminFeature->logBatchRemove($request));
        $router->get('/api/admin/log/stream', fn (Request $request) => $adminFeature->logStream($request));
        $router->get('/api/admin/staff-action-log/list', fn (Request $request) => $adminFeature->staffActionLogList($request));
        $router->get('/api/admin/log/staff-action-log', fn (Request $request) => $adminFeature->staffActionLogList($request));
        $router->get('/api/admin/user/log/login', fn (Request $request) => $admin->userLoginLogs($request));
        $router->post('/api/admin/user/switch-payed', fn (Request $request) => $admin->switchUserPayed($request));
        $router->post('/api/admin/user/switch-audit', fn (Request $request) => $admin->switchUserAudit($request));
        $router->post('/api/admin/user/rebate-balance/set', fn (Request $request) => $admin->setUserRebateBalance($request));
        $router->post('/api/admin/user/login-ticket', fn (Request $request) => $admin->userLoginTicket($request));
        $router->get('/api/admin/notification/list', fn (Request $request) => $adminFeature->notificationList($request));
        $router->post('/api/admin/notification/create', fn (Request $request) => $adminFeature->notificationCreate($request));
        $router->post('/api/admin/notification/edit', fn (Request $request) => $adminFeature->notificationEdit($request));
        $router->post('/api/admin/notification/remove', fn (Request $request) => $adminFeature->notificationRemove($request));
        $router->post('/api/admin/notification/switch-status', fn (Request $request) => $adminFeature->notificationSwitch($request));
        $router->get('/api/admin/notification/template/list', fn (Request $request) => $adminFeature->notificationTemplateList($request));
        $router->post('/api/admin/notification/template/create', fn (Request $request) => $adminFeature->notificationTemplateCreate($request));
        $router->post('/api/admin/notification/template/edit', fn (Request $request) => $adminFeature->notificationTemplateEdit($request));
        $router->post('/api/admin/notification/template/remove', fn (Request $request) => $adminFeature->notificationTemplateRemove($request));
        $router->post('/api/admin/notification/template/switch-status', fn (Request $request) => $adminFeature->notificationTemplateSwitch($request));
        $router->post('/api/admin/notification/template/test', fn (Request $request) => $adminFeature->notificationTemplateTest($request));
        $router->get('/api/admin/page/list', fn (Request $request) => $adminFeature->pageList($request));
        $router->post('/api/admin/page/create', fn (Request $request) => $adminFeature->pageCreate($request));
        $router->post('/api/admin/page/edit', fn (Request $request) => $adminFeature->pageEdit($request));
        $router->post('/api/admin/page/remove', fn (Request $request) => $adminFeature->pageRemove($request));
        $router->post('/api/admin/page/switch-status', fn (Request $request) => $adminFeature->pageSwitch($request));
        $router->get('/api/admin/polling/list', fn (Request $request) => $adminFeature->pollingList($request));
        $router->post('/api/admin/polling/create', fn (Request $request) => $adminFeature->pollingCreate($request));
        $router->post('/api/admin/polling/edit', fn (Request $request) => $adminFeature->pollingEdit($request));
        $router->post('/api/admin/polling/remove', fn (Request $request) => $adminFeature->pollingRemove($request));
        $router->post('/api/admin/polling/switch-status', fn (Request $request) => $adminFeature->pollingSwitch($request));
        $router->get('/api/admin/storage-channel/list', fn (Request $request) => $adminFeature->storageChannelList($request));
        $router->post('/api/admin/storage-channel/create', fn (Request $request) => $adminFeature->storageChannelCreate($request));
        $router->post('/api/admin/storage-channel/edit', fn (Request $request) => $adminFeature->storageChannelEdit($request));
        $router->post('/api/admin/storage-channel/remove', fn (Request $request) => $adminFeature->storageChannelRemove($request));
        $router->post('/api/admin/storage-channel/switch-status', fn (Request $request) => $adminFeature->storageChannelSwitch($request));
        $router->post('/api/admin/storage-channel/set-default', fn (Request $request) => $adminFeature->storageChannelDefault($request));
        $router->get('/api/admin/storage-channel/plugin/list', fn (Request $request) => $adminFeature->storagePluginList($request));
        $router->get('/api/admin/storage-channel/plugin/form-items', fn (Request $request) => $adminFeature->storagePluginFormItems($request));
        $router->post('/api/admin/storage-channel/test', fn (Request $request) => $adminFeature->storageChannelTest($request));
        $router->get('/api/admin/storage-file/list', fn (Request $request) => $adminFeature->storageFileList($request));
        $router->get('/api/admin/storage-file/stats', fn (Request $request) => $adminFeature->storageFileStats($request));
        $router->post('/api/admin/storage-file/remove', fn (Request $request) => $adminFeature->storageFileDelete($request));
        $router->get('/api/admin/storage-file/orphan/scan', fn (Request $request) => $adminFeature->storageOrphanScan($request));
        $router->post('/api/admin/storage-file/orphan/remove', fn (Request $request) => $adminFeature->storageOrphanDelete($request));
        $router->get('/api/admin/storage/channel/list', fn (Request $request) => $adminFeature->storageChannelList($request));
        $router->post('/api/admin/storage/channel/create', fn (Request $request) => $adminFeature->storageChannelCreate($request));
        $router->post('/api/admin/storage/channel/edit', fn (Request $request) => $adminFeature->storageChannelEdit($request));
        $router->post('/api/admin/storage/channel/remove', fn (Request $request) => $adminFeature->storageChannelRemove($request));
        $router->post('/api/admin/storage/channel/switch-status', fn (Request $request) => $adminFeature->storageChannelSwitch($request));
        $router->post('/api/admin/storage/channel/set-default', fn (Request $request) => $adminFeature->storageChannelDefault($request));
        $router->post('/api/admin/storage/channel/test', fn (Request $request) => $adminFeature->storageChannelTest($request));
        $router->get('/api/admin/storage/plugin/list', fn (Request $request) => $adminFeature->storagePluginList($request));
        $router->get('/api/admin/storage/plugin/form-items', fn (Request $request) => $adminFeature->storagePluginFormItems($request));
        $router->get('/api/admin/storage/file/list', fn (Request $request) => $adminFeature->storageFileList($request));
        $router->get('/api/admin/storage/file/stats', fn (Request $request) => $adminFeature->storageFileStats($request));
        $router->post('/api/admin/storage/file/delete', fn (Request $request) => $adminFeature->storageFileDelete($request));
        $router->get('/api/admin/storage/file/orphan/scan', fn (Request $request) => $adminFeature->storageOrphanScan($request));
        $router->post('/api/admin/storage/file/orphan-delete', fn (Request $request) => $adminFeature->storageOrphanDelete($request));
        $router->get('/api/admin/third-account/list', fn (Request $request) => $adminFeature->thirdAccountList($request));
        $router->post('/api/admin/third-account/create', fn (Request $request) => $adminFeature->thirdAccountCreate($request));
        $router->post('/api/admin/third-account/edit', fn (Request $request) => $adminFeature->thirdAccountEdit($request));
        $router->post('/api/admin/third-account/remove', fn (Request $request) => $adminFeature->thirdAccountRemove($request));
        $router->post('/api/admin/third-account/switch-status', fn (Request $request) => $adminFeature->thirdAccountSwitch($request));
        $router->get('/api/admin/third-account/log/list', fn (Request $request) => $adminFeature->thirdAccountLogList($request));
        $router->post('/api/admin/third-account/log/remove', fn (Request $request) => $adminFeature->thirdAccountLogRemove($request));
        $router->get('/api/admin/third-order-log/list', fn (Request $request) => $adminFeature->thirdOrderLogList($request));
        $router->post('/api/admin/third-order-log/remove', fn (Request $request) => $adminFeature->thirdOrderLogRemove($request));
        $router->post('/api/admin/third-order-log/report', fn (Request $request) => $adminFeature->thirdOrderLogReport($request));
        $router->get('/api/admin/plugin-runtime/status', fn (Request $request) => $adminFeature->pluginRuntimeStatus($request));
        $router->get('/api/admin/plugins/runtime', fn (Request $request) => $adminFeature->pluginRuntimeStatus($request));
        $router->get('/api/admin/third-accounts/list', fn (Request $request) => $adminFeature->thirdAccountList($request));
        $router->post('/api/admin/third-accounts/create', fn (Request $request) => $adminFeature->thirdAccountCreate($request));
        $router->post('/api/admin/third-accounts/edit', fn (Request $request) => $adminFeature->thirdAccountEdit($request));
        $router->post('/api/admin/third-accounts/remove', fn (Request $request) => $adminFeature->thirdAccountRemove($request));
        $router->post('/api/admin/third-accounts/switch-status', fn (Request $request) => $adminFeature->thirdAccountSwitch($request));
        $router->get('/api/admin/third-accounts/log/list', fn (Request $request) => $adminFeature->thirdAccountLogList($request));
        $router->post('/api/admin/third-accounts/log/remove', fn (Request $request) => $adminFeature->thirdAccountLogRemove($request));
        $router->get('/api/admin/sms-channel/list', fn (Request $request) => $adminFeature->smsChannelList($request));
        $router->post('/api/admin/sms-channel/create', fn (Request $request) => $adminFeature->smsChannelWrite($request));
        $router->post('/api/admin/sms-channel/edit', fn (Request $request) => $adminFeature->smsChannelWrite($request));
        $router->post('/api/admin/sms-channel/test', fn (Request $request) => $adminFeature->smsChannelTest($request));
        $router->get('/api/admin/sms-channel/plugin/list', fn (Request $request) => $adminFeature->smsPluginList($request));
        $router->get('/api/admin/sms-channel/plugin/form-items', fn (Request $request) => $adminFeature->smsPluginFormItems($request));
        $router->get('/api/admin/sms/channel/list', fn (Request $request) => $adminFeature->smsChannelList($request));
        $router->post('/api/admin/sms/channel/create', fn (Request $request) => $adminFeature->smsChannelWrite($request));
        $router->post('/api/admin/sms/channel/edit', fn (Request $request) => $adminFeature->smsChannelWrite($request));
        $router->post('/api/admin/sms/channel/remove', fn (Request $request) => $adminFeature->smsChannelWrite($request));
        $router->post('/api/admin/sms/channel/switch-status', fn (Request $request) => $adminFeature->smsChannelWrite($request));
        $router->post('/api/admin/sms/channel/test', fn (Request $request) => $adminFeature->smsChannelTest($request));
        $router->get('/api/admin/sms/plugin/list', fn (Request $request) => $adminFeature->smsPluginList($request));
        $router->get('/api/admin/sms/plugin/form-items', fn (Request $request) => $adminFeature->smsPluginFormItems($request));
        foreach (['stop', 'restart', 'update'] as $action) {
            $router->post('/api/admin/system/' . $action, fn (Request $request) => $adminFeature->externalSystemAction($request, $action));
        }
        $router->get('/api/admin/system/runtime', fn (Request $request) => $adminFeature->runtime($request));
        $router->get('/api/admin/system/check-version', fn (Request $request) => $adminFeature->checkVersion($request));
        $router->get('/api/admin/system/version-logs', fn (Request $request) => $adminFeature->versionLogs($request));
        $router->post('/api/admin/system/redis/test', fn (Request $request) => $adminFeature->redisTest($request));
        $router->post('/api/admin/system/redis/save', fn (Request $request) => $adminFeature->redisSave($request));
        foreach (['list', 'repos', 'install', 'remove'] as $action) {
            $router->match(['GET', 'POST'], '/api/admin/app-store/' . $action, fn (Request $request) => $adminFeature->appStore($request, $action));
        }
        $router->get('/api/admin/shared-channel/capability', fn (Request $request) => $adminFeature->sharedChannelCapability($request));
        $router->get('/api/admin/shared-channel/rule/list', fn (Request $request) => $adminFeature->sharedChannelList($request));
        $router->post('/api/admin/shared-channel/rule/create', fn (Request $request) => $adminFeature->sharedChannelWrite($request));
        $router->post('/api/admin/shared-channel/rule/edit', fn (Request $request) => $adminFeature->sharedChannelWrite($request));
        $router->post('/api/admin/shared-channel/rule/remove', fn (Request $request) => $adminFeature->sharedChannelRemove($request));
        $router->get('/api/admin/work-order/category/list', fn (Request $request) => $adminFeature->workOrderCategoryList($request));
        $router->post('/api/admin/work-order/category/create', fn (Request $request) => $adminFeature->workOrderCategoryCreate($request));
        $router->post('/api/admin/work-order/category/edit', fn (Request $request) => $adminFeature->workOrderCategoryEdit($request));
        $router->post('/api/admin/work-order/category/remove', fn (Request $request) => $adminFeature->workOrderCategoryRemove($request));
        $router->post('/api/admin/work-order/category/switch-status', fn (Request $request) => $adminFeature->workOrderCategorySwitch($request));
        $router->get('/api/admin/work-order/list', fn (Request $request) => $adminFeature->workOrderList($request));
        $router->get('/api/admin/work-order/detail', fn (Request $request) => $adminFeature->workOrderDetail($request));
        $router->post('/api/admin/work-order/edit', fn (Request $request) => $adminFeature->workOrderEdit($request));
        $router->post('/api/admin/work-order/remove', fn (Request $request) => $adminFeature->workOrderRemove($request));
        $router->post('/api/admin/work-order/switch-status', fn (Request $request) => $adminFeature->workOrderSwitch($request));
        $router->get('/api/admin/work-order/reply/list', fn (Request $request) => $adminFeature->workOrderReplyList($request));
        $router->post('/api/admin/work-order/reply/create', fn (Request $request) => $adminFeature->workOrderReplyCreate($request));
        $router->post('/api/admin/work-order/reply/edit', fn (Request $request) => $adminFeature->workOrderReplyEdit($request));
        $router->post('/api/admin/work-order/reply/remove', fn (Request $request) => $adminFeature->workOrderReplyRemove($request));
        $router->post('/api/admin/work-order/reply/switch-status', fn (Request $request) => $adminFeature->workOrderReplySwitch($request));
        $router->get('/api/admin/work-order/cate/list', fn (Request $request) => $adminFeature->workOrderCategoryList($request));
        $router->post('/api/admin/work-order/cate/create', fn (Request $request) => $adminFeature->workOrderCategoryCreate($request));
        $router->post('/api/admin/work-order/cate/edit', fn (Request $request) => $adminFeature->workOrderCategoryEdit($request));
        $router->post('/api/admin/work-order/cate/remove', fn (Request $request) => $adminFeature->workOrderCategoryRemove($request));
        $router->post('/api/admin/work-order/cate/switch-status', fn (Request $request) => $adminFeature->workOrderCategorySwitch($request));
        $router->get('/api/admin/work-order/list/list', fn (Request $request) => $adminFeature->workOrderList($request));
        $router->post('/api/admin/work-order/list/create', fn (Request $request) => $adminFeature->workOrderEdit($request));
        $router->post('/api/admin/work-order/list/edit', fn (Request $request) => $adminFeature->workOrderEdit($request));
        $router->post('/api/admin/work-order/list/remove', fn (Request $request) => $adminFeature->workOrderRemove($request));
        $router->post('/api/admin/work-order/list/switch-status', fn (Request $request) => $adminFeature->workOrderSwitch($request));
        $router->get('/api/admin/channel/gateway/list', fn (Request $request) => $adminFeature->channelGatewayList($request));
        $router->post('/api/admin/channel/gateway/create', fn (Request $request) => $adminFeature->channelGatewayCreate($request));
        $router->post('/api/admin/channel/gateway/edit', fn (Request $request) => $adminFeature->channelGatewayEdit($request));
        $router->post('/api/admin/channel/gateway/remove', fn (Request $request) => $adminFeature->channelGatewayRemove($request));
        $router->post('/api/admin/channel/gateway/switch-status', fn (Request $request) => $adminFeature->channelGatewaySwitch($request));
        $router->post('/api/admin/channel/gateway/batch-remove', fn (Request $request) => $adminFeature->channelGatewayBatchRemove($request));
        $router->post('/api/admin/channel/gateway/batch-import', fn (Request $request) => $adminFeature->channelGatewayBatchImport($request));
        $router->get('/api/admin/domain-white/list', fn (Request $request) => $adminFeature->domainWhiteList($request));
        $router->post('/api/admin/domain-white/create', fn (Request $request) => $adminFeature->domainWhiteCreate($request));
        $router->post('/api/admin/domain-white/edit', fn (Request $request) => $adminFeature->domainWhiteEdit($request));
        $router->post('/api/admin/domain-white/remove', fn (Request $request) => $adminFeature->domainWhiteRemove($request));
        $router->post('/api/admin/domain-white/switch-status', fn (Request $request) => $adminFeature->domainWhiteSwitch($request));
        $router->get('/api/admin/black-data/list', fn (Request $request) => $adminFeature->blackDataList($request));
        $router->post('/api/admin/black-data/create', fn (Request $request) => $adminFeature->blackDataCreate($request));
        $router->post('/api/admin/black-data/edit', fn (Request $request) => $adminFeature->blackDataEdit($request));
        $router->post('/api/admin/black-data/remove', fn (Request $request) => $adminFeature->blackDataRemove($request));
        $router->post('/api/admin/black-data/switch-status', fn (Request $request) => $adminFeature->blackDataSwitch($request));
        $router->post('/api/admin/black-data/batch-generate', fn (Request $request) => $adminFeature->blackDataBatchGenerate($request));
        $router->post('/api/admin/black-data/refresh-cache', fn (Request $request) => $adminFeature->blackDataRefreshCache($request));
        $router->get('/api/admin/meal/list', fn (Request $request) => $adminFeature->mealList($request));
        $router->post('/api/admin/meal/create', fn (Request $request) => $adminFeature->mealCreate($request));
        $router->post('/api/admin/meal/edit', fn (Request $request) => $adminFeature->mealEdit($request));
        $router->post('/api/admin/meal/remove', fn (Request $request) => $adminFeature->mealRemove($request));
        $router->post('/api/admin/meal/switch-status', fn (Request $request) => $adminFeature->mealSwitch($request));
        $router->get('/api/admin/system-order/list', fn (Request $request) => $adminFeature->systemOrderList($request));
        $router->post('/api/admin/system-order/remove', fn (Request $request) => $adminFeature->systemOrderRemove($request));
        $router->get('/api/admin/cards/groups/list', fn (Request $request) => $adminFeature->cardGroupList($request));
        $router->post('/api/admin/cards/groups/create', fn (Request $request) => $adminFeature->cardGroupCreate($request));
        $router->post('/api/admin/cards/groups/edit', fn (Request $request) => $adminFeature->cardGroupEdit($request));
        $router->post('/api/admin/cards/groups/remove', fn (Request $request) => $adminFeature->cardGroupRemove($request));
        $router->post('/api/admin/cards/groups/switch-status', fn (Request $request) => $adminFeature->cardGroupSwitch($request));
        $router->get('/api/admin/cards/list', fn (Request $request) => $adminFeature->cardList($request));
        $router->post('/api/admin/cards/create', fn (Request $request) => $adminFeature->cardCreate($request));
        $router->post('/api/admin/cards/edit', fn (Request $request) => $adminFeature->cardEdit($request));
        $router->post('/api/admin/cards/remove', fn (Request $request) => $adminFeature->cardRemove($request));
        $router->post('/api/admin/cards/switch-status', fn (Request $request) => $adminFeature->cardSwitch($request));
        $router->post('/api/admin/cards/batch-generate', fn (Request $request) => $adminFeature->cardBatchGenerate($request));
        $router->get('/api/admin/area/list', fn (Request $request) => $adminFeature->areaList($request));
        $router->post('/api/admin/area/create', fn (Request $request) => $adminFeature->areaCreate($request));
        $router->post('/api/admin/area/edit', fn (Request $request) => $adminFeature->areaEdit($request));
        $router->post('/api/admin/area/remove', fn (Request $request) => $adminFeature->areaRemove($request));
        $router->post('/api/admin/area/switch-status', fn (Request $request) => $adminFeature->areaSwitch($request));
        $router->get('/api/admin/proxy-pool/list', fn (Request $request) => $adminFeature->proxyPoolList($request));
        $router->post('/api/admin/proxy-pool/create', fn (Request $request) => $adminFeature->proxyPoolCreate($request));
        $router->post('/api/admin/proxy-pool/edit', fn (Request $request) => $adminFeature->proxyPoolEdit($request));
        $router->post('/api/admin/proxy-pool/remove', fn (Request $request) => $adminFeature->proxyPoolRemove($request));
        $router->post('/api/admin/proxy-pool/switch-status', fn (Request $request) => $adminFeature->proxyPoolSwitch($request));
        foreach (['list', 'create', 'edit', 'remove', 'switch-status', 'import', 'export'] as $action) {
            $methods = in_array($action, ['list', 'export'], true) ? ['GET'] : ['POST'];
            $router->match($methods, '/api/admin/proxy-pool-items/' . $action, fn (Request $request) => $adminFeature->proxyPoolItems($request, $action));
        }
        $router->get('/api/admin/option/templates', fn (Request $request) => $adminFeature->optionTemplates($request));
        $router->get('/api/admin/option/captcha/verify', fn (Request $request) => $admin->getOptionGroup($request, 'captcha'));
        $router->get('/api/admin/connect/items', fn (Request $request) => $adminFeature->connectItems($request));
        $router->get('/api/admin/connect/templates', fn (Request $request) => $adminFeature->connectTemplates($request));
        $router->get('/api/admin/service-account-pool/list', fn (Request $request) => $adminFeature->serviceAccountPoolList($request));
        $router->get('/api/admin/qrcode-templates/list', fn (Request $request) => $adminFeature->qrcodeTemplateList($request));
        $router->post('/api/admin/qrcode-templates/create', fn (Request $request) => $adminFeature->qrcodeTemplateCreate($request));
        $router->post('/api/admin/qrcode-templates/edit', fn (Request $request) => $adminFeature->qrcodeTemplateEdit($request));
        $router->post('/api/admin/qrcode-templates/remove', fn (Request $request) => $adminFeature->qrcodeTemplateRemove($request));
        $router->post('/api/admin/qrcode-templates/switch-status', fn (Request $request) => $adminFeature->qrcodeTemplateSwitch($request));
        $router->get('/api/admin/templates/{type}/list', fn (Request $request, string $type) => $adminFeature->templateList($request, $type));
        $router->get('/api/admin/templates/list', fn (Request $request) => $adminFeature->templateApiList($request));
        $router->get('/api/admin/templates/types', fn (Request $request) => $adminFeature->templateTypes($request));
        $router->get('/api/admin/templates/screenshot', fn (Request $request) => $adminFeature->templateScreenshot($request));
        $router->get('/api/admin/templates/{type}/screenshot', fn (Request $request, string $type) => $adminFeature->templateScreenshot($request, $type));
        $router->get('/api/admin/third-connect-chat/list', fn (Request $request) => $adminFeature->thirdConnectChatList($request));
        $router->post('/api/admin/third-connect-chat/create', fn (Request $request) => $adminFeature->thirdConnectChatCreate($request));
        $router->post('/api/admin/third-connect-chat/edit', fn (Request $request) => $adminFeature->thirdConnectChatEdit($request));
        $router->post('/api/admin/third-connect-chat/remove', fn (Request $request) => $adminFeature->thirdConnectChatRemove($request));
        $router->post('/api/admin/third-connect-chat/switch-status', fn (Request $request) => $adminFeature->thirdConnectChatSwitch($request));
        $router->get('/api/admin/tools/config-wizard/check', fn (Request $request) => $adminFeature->configWizardCheck($request));
        $router->get('/api/admin/app-items/list', fn (Request $request) => $adminFeature->appItemsList($request));
        $router->post('/api/admin/app-items/enable', fn (Request $request) => $adminFeature->appItemsAction($request, 'enable'));
        $router->post('/api/admin/app-items/disable', fn (Request $request) => $adminFeature->appItemsAction($request, 'disable'));
        $router->post('/api/admin/app-items/reload', fn (Request $request) => $adminFeature->appItemsAction($request, 'reload'));
        $router->post('/api/admin/app-items/uninstall', fn (Request $request) => $adminFeature->appItemsAction($request, 'uninstall'));
        $router->post('/api/admin/app-items/batch-enable', fn (Request $request) => $adminFeature->appItemsBatchAction($request, 'enable'));
        $router->post('/api/admin/app-items/batch-disable', fn (Request $request) => $adminFeature->appItemsBatchAction($request, 'disable'));
        $router->post('/api/admin/app-items/batch-uninstall', fn (Request $request) => $adminFeature->appItemsBatchAction($request, 'uninstall'));
        $router->get('/api/admin/app-items/scan-local-plugins', fn (Request $request) => $adminFeature->appItemsScanLocalPlugins($request));
        $router->post('/api/admin/app-items/load-local-plugin', fn (Request $request) => $adminFeature->appItemsLoadLocalPlugin($request));
        $router->post('/api/admin/app-items/scan-templates', fn (Request $request) => $adminFeature->appItemsScanTemplates($request));
        $router->post('/api/admin/app-items/load-local-template', fn (Request $request) => $adminFeature->appItemsLoadLocalTemplate($request));
        foreach (['/api', '/api/admin'] as $prefix) {
            $router->post($prefix . '/user/create', fn (Request $request) => $admin->createUser($request));
            $router->post($prefix . '/user/edit', fn (Request $request) => $admin->editUser($request));
            $router->post($prefix . '/user/remove', fn (Request $request) => $admin->removeUser($request));
            $router->post($prefix . '/user/switch-status', fn (Request $request) => $admin->switchUserStatus($request));
            $router->post($prefix . '/user/balance/set', fn (Request $request) => $admin->setUserBalance($request));
            $router->post($prefix . '/user/login-ticket', fn (Request $request) => $admin->userLoginTicket($request));
            $router->post($prefix . '/notice/create', fn (Request $request) => $admin->createNotice($request));
            $router->post($prefix . '/notice/edit', fn (Request $request) => $admin->editNotice($request));
            $router->post($prefix . '/notice/remove', fn (Request $request) => $admin->removeNotice($request));
            $router->post($prefix . '/notice/switch-status', fn (Request $request) => $admin->switchNoticeStatus($request));
            $router->post($prefix . '/pay-type/create', fn (Request $request) => $admin->createPayType($request));
            $router->post($prefix . '/pay-type/edit', fn (Request $request) => $admin->editPayType($request));
            $router->post($prefix . '/pay-type/remove', fn (Request $request) => $admin->removePayType($request));
            $router->post($prefix . '/pay-type/switch-status', fn (Request $request) => $admin->switchPayTypeStatus($request));
            $router->post($prefix . '/channel/create', fn (Request $request) => $admin->createChannel($request));
            $router->post($prefix . '/channel/edit', fn (Request $request) => $admin->editChannel($request));
            $router->post($prefix . '/channel/remove', fn (Request $request) => $admin->removeChannel($request));
            $router->post($prefix . '/channel/switch-status', fn (Request $request) => $admin->switchChannelStatus($request));
            $router->get($prefix . '/channel/detail', fn (Request $request) => $admin->channelDetail($request));
            $router->post($prefix . '/channel/account/create', fn (Request $request) => $admin->createChannelAccount($request));
            $router->post($prefix . '/channel/account/edit', fn (Request $request) => $admin->editChannelAccount($request));
            $router->post($prefix . '/channel/account/remove', fn (Request $request) => $admin->removeChannelAccount($request));
            $router->post($prefix . '/channel/account/switch-status', fn (Request $request) => $admin->switchChannelAccountStatus($request));
            $router->post($prefix . '/order/remove', fn (Request $request) => $admin->removeOrder($request));
            $router->post($prefix . '/order/batch-remove', fn (Request $request) => $admin->batchRemoveOrders($request));
            $router->post($prefix . '/order/close', fn (Request $request) => $admin->closeOrder($request));
            $router->post($prefix . '/order/wait', fn (Request $request) => $admin->waitOrder($request));
            $router->post($prefix . '/order/success', fn (Request $request) => $admin->successOrder($request));
            $router->post($prefix . '/order/callback', fn (Request $request) => $admin->callbackOrder($request));
            $router->post($prefix . '/order/action', fn (Request $request) => $admin->orderAction($request));
            $router->post($prefix . '/order/create-test', fn (Request $request) => $admin->createTestOrder($request));
            $router->get($prefix . '/option/{group}', fn (Request $request, string $group) => $admin->getOptionGroup($request, $group));
            $router->post($prefix . '/option/{group}', fn (Request $request, string $group) => $admin->setOptionGroup($request, $group));
            $router->post($prefix . '/plugins/start', fn (Request $request) => $admin->pluginAction($request, 'start'));
            $router->post($prefix . '/plugins/stop', fn (Request $request) => $admin->pluginAction($request, 'stop'));
            $router->post($prefix . '/plugins/enable', fn (Request $request) => $admin->pluginAction($request, 'enable'));
            $router->post($prefix . '/plugins/disable', fn (Request $request) => $admin->pluginAction($request, 'disable'));
            $router->post($prefix . '/plugins/remove', fn (Request $request) => $admin->pluginAction($request, 'remove'));
            $router->post($prefix . '/plugins/refresh', fn (Request $request) => $admin->pluginAction($request, 'refresh'));
            $router->post($prefix . '/plugins/set-options', fn (Request $request) => $admin->pluginSetOptions($request));
        }
        $router->get('/api/admin/option/compliance', fn (Request $request) => $admin->compliance($request));
        $router->post('/api/admin/option/compliance', fn (Request $request) => $admin->confirmCompliance($request));
        $router->get('/api/pay/conf', fn () => $pay->config());
        $router->post('/api/order/info', fn (Request $request) => $pay->orderInfo($request));
        $router->post('/api/order/status', fn (Request $request) => $pay->orderStatus($request));
        $router->post('/api/order/chose-type', fn (Request $request) => $pay->chooseType($request));
        $router->post('/api/order/audio', fn (Request $request) => $pay->audio($request));
        $router->post('/api/pay/types', fn (Request $request) => $pay->types($request));
        $router->post('/api/order/qrcode', fn (Request $request) => $pay->qrcode($request));
        $router->post('/api/cashier/parse', fn (Request $request) => $pay->cashierParse($request));
        $router->post('/api/order/create-cashier', fn (Request $request) => $pay->createCashier($request));
        $router->any('/xpay/epay/submit.php', fn (Request $request) => $epay->submit($request));
        $router->any('/xpay/epay/mapi.php', fn (Request $request) => $epay->mapi($request));
        $router->any('/xpay/epay/notify.php', fn (Request $request) => $epay->notify($request));
        $router->any('/xpay/epay/api.php', fn (Request $request) => $epay->api($request));
        $router->any('/xpay/hupijiao', fn (Request $request) => $epay->unsupported($request, 'hupijiao'));
        $router->any('/xpay/hupijiao/payment/do.html', fn (Request $request) => $epay->unsupported($request, 'hupijiao/payment/do.html'));
        $router->any('/xpay/epayn/api/pay/submit', fn (Request $request) => $epay->unsupported($request, 'epayn/api/pay/submit'));
        $router->any('/xpay/epayn/api/pay/create', fn (Request $request) => $epay->unsupported($request, 'epayn/api/pay/create'));
        $router->any('/xpay/epayn/api/pay/query', fn (Request $request) => $epay->unsupported($request, 'epayn/api/pay/query'));
        $router->any('/api/epay/submit.php', fn (Request $request) => $epay->submit($request));
        $router->any('/api/epay/mapi.php', fn (Request $request) => $epay->mapi($request));
        $router->any('/api/epay/notify.php', fn (Request $request) => $epay->notify($request));
        $router->any('/api/epay/api.php', fn (Request $request) => $epay->api($request));
        $router->post('/api/user/profile', fn (Request $request) => $merchantFeature->setProfile($request));
        $router->post('/api/user/send-bind-email-code', fn (Request $request) => $merchantFeature->sendBindEmailCode($request));
        $router->post('/api/user/bind-email', fn (Request $request) => $merchantFeature->bindEmail($request));
        $router->post('/api/user/send-bind-phone-code', fn (Request $request) => $merchantFeature->sendBindPhoneCode($request));
        $router->post('/api/user/bind-phone', fn (Request $request) => $merchantFeature->bindPhone($request));
        $router->get('/api/user/sms-credit/info', fn (Request $request) => $merchantFeature->smsCreditInfo($request));
        $router->post('/api/user/sms-credit/buy', fn (Request $request) => $merchantFeature->smsCreditBuy($request));
        $router->post('/api/user/safe/mfa', fn (Request $request) => $merchantFeature->mfa($request));
        $router->post('/api/user/safe/unmfa', fn (Request $request) => $merchantFeature->unmfa($request));
        $router->post('/api/user/bind-wechat', fn (Request $request) => $merchantFeature->bindWechat($request));
        $router->post('/api/user/unbind-wechat', fn (Request $request) => $merchantFeature->unbindWechat($request));
        $router->post('/api/user/bind-tg', fn (Request $request) => $merchantFeature->bindTelegram($request));
        $router->post('/api/user/unbind-tg', fn (Request $request) => $merchantFeature->unbindTelegram($request));
        $router->get('/api/user/connect/channels', fn (Request $request) => $merchantFeature->connectChannels($request));
        $router->get('/api/user/connect/list', fn (Request $request) => $merchantFeature->connectList($request));
        $router->get('/api/user/connect/bind-url', fn (Request $request) => $merchantFeature->connectUrl($request));
        $router->post('/api/user/connect/qrcode', fn (Request $request) => $merchantFeature->connectQrcode($request));
        $router->post('/api/user/connect/bind', fn (Request $request) => $merchantFeature->connectAction($request));
        $router->post('/api/user/connect/unbind', fn (Request $request) => $merchantFeature->connectAction($request));
        $router->post('/api/user/app-login-ticket', fn (Request $request) => $merchantFeature->appLoginTicket($request));
        $router->post('/api/user/app-login-ticket-check', fn (Request $request) => $merchantFeature->appLoginTicket($request, true));
        $router->get('/api/user/passkey/list', fn (Request $request) => $merchantFeature->passkey($request, 'list'));
        $router->post('/api/user/passkey/begin', fn (Request $request) => $merchantFeature->passkey($request, 'begin'));
        $router->post('/api/user/passkey/finish', fn (Request $request) => $merchantFeature->passkey($request, 'finish'));
        $router->post('/api/user/passkey/rename', fn (Request $request) => $merchantFeature->passkey($request, 'rename'));
        $router->post('/api/user/passkey/remove', fn (Request $request) => $merchantFeature->passkey($request, 'remove'));
        $router->post('/api/user/passkey/auth/begin', fn (Request $request) => $merchantFeature->passkey($request, 'auth-begin'));
        $router->post('/api/user/passkey/auth/finish', fn (Request $request) => $merchantFeature->passkey($request, 'auth-finish'));
        $router->get('/api/user/rsa-key/info', fn (Request $request) => $merchantFeature->rsaKey($request, 'info'));
        $router->post('/api/user/rsa-key/generate', fn (Request $request) => $merchantFeature->rsaKey($request, 'generate'));
        $router->get('/api/tickets/status', fn (Request $request) => $merchantFeature->ticketsStatus($request));
        $router->post('/api/tickets/status', fn (Request $request) => $merchantFeature->ticketsStatus($request));
        $router->get('/api/tickets/data', fn (Request $request) => $merchantFeature->ticketsData($request));
        $router->post('/api/tickets/data', fn (Request $request) => $merchantFeature->ticketsData($request));
        $router->post('/ticket/status', fn (Request $request) => $merchantFeature->ticketsStatus($request));
        $router->post('/ticket/data', fn (Request $request) => $merchantFeature->ticketsData($request));
        $router->get('/api/work-order/cate/list', fn (Request $request) => $merchantFeature->workOrderCategories($request));
        $router->get('/api/work-order/cate', fn (Request $request) => $merchantFeature->workOrderCategories($request));
        $router->get('/api/work-order/list', fn (Request $request) => $merchantFeature->workOrderList($request));
        $router->post('/api/work-order/create', fn (Request $request) => $merchantFeature->workOrderCreate($request));
        $router->get('/api/work-order/reply/list', fn (Request $request) => $merchantFeature->workOrderReplies($request));
        $router->post('/api/work-order/reply', fn (Request $request) => $merchantFeature->workOrderReply($request));
        $router->post('/api/upload/avatar', fn (Request $request) => $merchantFeature->upload($request, 'avatar'));
        $router->post('/api/upload/images', fn (Request $request) => $merchantFeature->upload($request, 'images'));
        $router->post('/api/upload/sign', fn (Request $request) => $merchantFeature->uploadSign($request));
        $router->post('/api/upload/confirm', fn (Request $request) => $merchantFeature->uploadConfirm($request));
        $router->get('/api/register/captcha', fn (Request $request) => $merchantFeature->registerCaptcha($request));
        $router->post('/api/register', fn (Request $request) => $merchantFeature->register($request));
        $router->post('/api/register/email', fn (Request $request) => $merchantFeature->externalEmailFeature($request, 'register.email'));
        $router->post('/api/login/email-code', fn (Request $request) => $merchantFeature->externalEmailFeature($request, 'login.email-code'));
        $router->post('/api/login/email', fn (Request $request) => $merchantFeature->externalEmailFeature($request, 'login.email'));
        $router->post('/api/user/rgorder', fn (Request $request) => $merchantFeature->rgorder($request, 'create'));
        $router->get('/api/user/rgorder/status', fn (Request $request) => $merchantFeature->rgorder($request, 'status'));
        $router->match(['GET', 'POST'], '/api/report/third-account', fn (Request $request) => $merchantFeature->reportThirdAccount($request, 'report'));
        $router->match(['GET', 'POST'], '/api/report/third-account/head', fn (Request $request) => $merchantFeature->reportThirdAccount($request, 'head'));
        $router->match(['GET', 'POST'], '/api/report/third-account/heart', fn (Request $request) => $merchantFeature->reportThirdAccount($request, 'heart'));
        $router->post('/api/report/xiaodai/api', fn (Request $request) => $merchantFeature->reportXiaodai($request));
        $router->match(['GET', 'POST'], '/api/report/{pid}/pc', fn (Request $request, string $pid) => $merchantFeature->reportMerchant($request, (int) $pid, 'pc'));
        $router->match(['GET', 'POST'], '/api/report/{pid}/heart', fn (Request $request, string $pid) => $merchantFeature->reportMerchant($request, (int) $pid, 'heart'));
        $router->match(['GET', 'POST'], '/api/report/{pid}', fn (Request $request, string $pid) => $merchantFeature->reportMerchant($request, (int) $pid, 'mobile'));
        $router->match(['GET', 'POST'], '/api/report/{action}', fn (Request $request, string $action) => $merchantFeature->externalReport($request, $action));
        $router->post('/api/forget', fn (Request $request) => $merchantFeature->externalAccountRecovery($request, 'forget'));
        $router->post('/api/forget/email', fn (Request $request) => $merchantFeature->externalAccountRecovery($request, 'email'));
        $router->dispatch($request);
    }
}
